travis:
  secure:
    BINSTAR_TOKEN: hPP/OIAPreu2Bp72rfInTZjPNhvrJXMwKsuweS3e1ag3CxQ4kmiZRJ8o2MuMepzun8XqT6icS2l1REmwy7PQ9Vta9UizszLXB/6VI+9wmc0Gz5MaDYMtD17iK2+ge9ah30PlFgJBAd2npKig019ZfKOKE/svG9K9td0HLzEZiF9UkYOfNqYoQlTJ4ur/8NETvKsfq8YQHvDm7DMaDyqJzd/4WoMyL6gwUaUb3KMzryE4MwBlTQF2M8lR4PSLdGYrlv05wARrNwlSCM4K7+9Bt+NU2tthEC87qMnwGzlmfJnMx8M1HNYAiMH83KTw64wdyybN7y0oWeAr6irspM9CvRFHYpacrhCAjBnCfNCZBFDhwkr3SoGHh73eYTD6s116NaeFyJW+/2Y4n+pInKdqxQSUBn6JiGy1vNFdnGaFzi/d8hX1CdxxtifjLeHf8uQj42wN1RoAbJWnJJQRlJJTssF5I367vuamZXpQe3YsiU4V7/Q8GjEEvR13FMq4/GPP6+XiOdwm8j9nrnG/nW54L9LEKgjoKMniDdDGl4W7IxFua5BQJL6G54r+UHvA34jq/lkgBHuiRVBLmnj9+YZmeyqfH7HvaPg8D0sOTv29LP3Zjn3NbcmSCwndLcYTNZsMVbMPLauNqbNJtW11WBD7uFHmy57We8vRq2sBdUAwG5w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
