travis:
  secure:
    BINSTAR_TOKEN: KJCP+E8pOerl3u4EBQgWns03yVuoczegRXUdu73iLWTZ7sKnIdTV1/E6HMbuXnOlWbM0RUg88iSPkj6XtGwvwqIwMWjP1fciBZj0K1QOGhDeWnKiaVakLOXCkMSp3msBxYyS6dMVlYlECbyP4yc3dwtciOyo47lU53dkz8ut93/0rr5WGmUyvvafgTskox8xGVvuNb/N7XSQA5WBRSRRQ/2YIlYBe09DjtMJWZ0Lwfx8PZHGiT2yx27gBpnTr0qb/9hX56NzH2ad1JBk7MG9RyaH+jWH0WC1c6OWQ9IkNi59mxLPLSD4rkD12GmcoztrgwEaWeZIixumZkEEoqbVy9Evy1y5BbZ13WaFCHvGCrvS56cG7CVACcsDk79RZSxfPniMJp6u0l2XhgNdE/4dScS8VxabgrPqd014S51ayvTNs01EFMTVO0s2dbv0yNsvHqYwQf6i8XloODk1GKAs6puOqrHpCaRCD8qbHzeI2A3UO1lB8XLXVczGWnrylld0i00GCqy980y6gHJSGa+JVg85piqM8JqPok2CLkcUlSMVV0/gGG1PXnfYY7hRN0S0DrL4lEvQOk04eY20Yv+vHyYlr2odiQ3Kig+4Tz0EsnB5nUl+YUAWo2TzdBCYIfcr7kwLwjxT4RKK6fqwdNKcUp5ubAUhAuSceRxupnX/3qs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
